### ISSUE TITLE
create-project does not ask anything

### ISSUE THREAD

**Issue by elboletaire** [UseMuffin/Skeleton#6]
Following the readme, using `composer create-project muffin/skeleton CustomName` should trigger the plugin's console postInstall script, but it doesn't.

Shouldn't I add something to my main composer.json file? Maybe overwrite the default postInstall hook? Or add another one?

**Comment by ADmad** [comment]
We probably need to change "post-install-cmd" to "post-create-project-cmd".

**Comment by jadb** [comment]
huh.. this was working on earlier version of composer (1.0.0-alpha10).

I will look into it.

**Comment by jadb** [comment]
BTW, its the pre-install that handles all the questionnaire (look at first line of GIF in README). But for some unknown reason to me yet, it just stopped working. Needs digging.

**Comment by ADmad** [comment]
The triggering of hooks has changed since composer 1.0. IIRC install hooks are only run if composer.lock exists.

**Comment by jadb** [comment]
Testing those things is tricky but I was lucky on the first shot: https://github.com/UseMuffin/Skeleton/commit/9ff68fb8ae06aa378499849c639a198ee1c4b553

I released a new tag. @elboletaire, please let me know if it works for you now.

**Comment by elboletaire** [comment]
It seems that you have not linked packagist with the github project. The latest available version on packagist is 1.0.0.

BTW, using `dev-master` as the version seems to work as expected :smiley:

**Comment by jadb** [comment]
Turns out there was a broken branch stopping packagist. Fixed.

<img width="506" alt="screen shot 2016-05-20 at 9 12 17 am" src="https://cloud.githubusercontent.com/assets/33527/15428738/2cfd8fd4-1e6b-11e6-907f-9273e2f9719b.png">
